### ISSUE TITLE
Index corruptions when force reindexing and aborting app

### ISSUE THREAD

**Issue by staltz** [ssbc/jitdb#234]
The steps to reproduce this bug are:

**Good case**

1. Run Manyverse 0.2209.2 on Android
2. Run "Force reindex"
3. Keep the app open to let it complete
4. Once it completes, the public feed shows threads in the correct order
5. Download all the indexes to my desktop

**Bad case**

1. Run Manyverse 0.2209.2 on Android
2. Run "Force reindex"
3. Once the progress bar is around 12%, kill the app
4. Re-open the app, and let it complete indexing
6. Once it completes, the public feed shows threads in the wrong order, and/or shows very old threads at the very top of the feed
7. Download all the indexes to my desktop

I can somewhat reliably reproduce this, so I studied the diff between the good and bad cases above. Here's some things I discovered: 

* Difference between good `seq.index` and bad `seq.index` "count" field is 171000
* `seq.index` good-vs-bad diff starts at byte 0xA6FE0
* `timestamp.index` good-vs-bad diff starts at byte 0x14DFC0
* 0xA6FE0 = 684000
* 0x14DFC0 = 1368000
* Bad seq.index at byte 0xA6FE0 jumps/skips exactly 684000 records ahead
* 1368000 is exactly 684000 times 2 (!)

**Comment by arj03** [comment]
Well timestamp is a Float64Array and sequence is a Int32Array, so it makes sense that it should be able exactly byte*2 if they fail at the same point in time. So the question must be why it fails at that point I think.

**Comment by arj03** [comment]
And 684000 / 4 bytes should mean at index 171000 and this matches "count" field is 171000

**Comment by staltz** [comment]
Yeah something doesn't seem right with calculating the seq from the offset, in jitdb:

https://github.com/ssbc/jitdb/blob/e451d03c6f9f7c16e2b5d4fddbcd714cbfe180f0/index.js#L578

```
calculate min: offset=2659611 and seq=1
```
